version: '3.8'

networks:
  app:
    driver: bridge

volumes:
  redis_data:

services:
  app:
    build: .
    networks:
      - app
    ports:
      - "5001:5000"
    expose:
      - 5000
    depends_on:
      - redis
  worker:
    build: .
    networks:
      - app
    depends_on:
      - redis
    command: "celery -A run.celery_app worker --loglevel INFO -E"
    environment:
      NOTIFY_CHANNEL_ID: ""
      NOTIFY_API_TOKEN: ""
      NOTIFY_API_ENDPOINT: ""
  flower:
    build: .
    networks:
      - app
    depends_on:
      - redis
    ports:
      - "5555:5555"
    command: "celery -A run.celery_app --broker=redis://redis:6379/0 flower"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app
    volumes:
      - redis_data:/bitnami/redis/data
    expose:
      - 6379
    ports:
      - "127.0.0.1:6379:6379"
