version: '3.8'

networks:
  app:
    driver: bridge

volumes:
  redis_data:

services:
  app:
    build: .
    networks:
      - app
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - redis
  worker-1:
    build: .
    networks:
      - app
    depends_on:
      - redis
    command: "celery -A run.celery_app worker --loglevel INFO"
  worker-2:
    build: .
    networks:
      - app
    depends_on:
      - redis
    command: "celery -A run.celery_app worker --loglevel INFO"
  worker-3:
    build: .
    networks:
      - app
    depends_on:
      - redis
    command: "celery -A run.celery_app worker --loglevel INFO"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app
    volumes:
      - redis_data:/bitnami/redis/data
    expose:
      - 6379
    ports:
      - 127.0.0.1:6379:6379
